name: s3 sync porfolio

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sync-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Building page
        run: npm install && npm run build

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: github-actions-aws
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Sync files bucket
        run: aws s3 sync ./dist/ s3://${{secrets.AWS_BUCKET_NAME}} --delete